import type { Product } from "../types/ProductType"
import photoExample from '../assets/hotdog-ex.jpg'

export const products: Product[] = [
    // {
    //     id: -1,
    //     title: "Batata Frita",
    //     price: 8,
    //     photo: photoExample,
    //     description: "Batatas Fritas no óleo",
    //     offer: false,
    //     categorieId: 2,
    //     storage: 99999,
    //     disponible: true,
    //     categorieName: "Fritas",
    // },

    //     {
    //     id: -1,
    //     title: "",
    //     price: 8,
    //     photo: "",
    //     description: "",
    //     offer: false,
    //     categorieId: 2,
    //     storage: 99999,
    //     disponible: true,
    //     categorieName: "",
    // },

    // HOTDOGS
    {
        id: 0,
        title: "Dog Bacon",
        price: 24,
        photo: "https://instadelivery-public.nyc3.cdn.digitaloceanspaces.com/itens/177154364669979c5ea2a3f_75_75.jpeg",
        description: "Pão, Salsicha, bacon , cebola , tomate, batata palha, purê de batata, maionese, ketchup e cheddar",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 1,
        title: "Dog Calabresa c/bacon",
        price: 25,
        photo: "https://instadelivery-public.nyc3.cdn.digitaloceanspaces.com/itens/177154364669979c5ea2a3f_75_75.jpeg",
        description: "Pão, Salsicha, calabresa ,bacon , cebola refogada , tomate, batata palha, purê de batata, maionese, ketchup e Catupiry",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 2,
        title: "Dog calabresa",
        price: 23,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020151_70N7_.jpeg",
        description: "Pão, Salsicha, calabresa , cebola refogada , tomate, batata palha, purê de batata, maionese, ketchup e Catupiry",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 3,
        title: "Dog Calabresa c/bacon",
        price: 26,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020156_B362_.jpeg",
        description: "Pão, Salsicha, calabresa ,bacon , cebola refogada , tomate, batata palha, purê de batata, maionese, ketchup e Catupiry",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 4,
        title: "Dog calabresa c/queijo",
        price: 8,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020154_0I4N_.jpeg",
        description: "Pão, Salsicha, calabresa , queijo mussarela, cebola refogada , tomate, batata palha, purê de batata, maionese, ketchup e catchup",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 5,
        title: "Dog carne de sol",
        price: 29,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020144_3WDJ_.jpeg",
        description: "Pão, Salsicha, carne de sol , cebola refogada , tomate, batata palha, purê de batata, maionese, ketchup e cheddar",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 6,
        title: "Dog Carne de sol c/Nata",
        price: 31,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020147_12WN_.jpeg",
        description: "Pão, Salsicha, carne de sol c/nata, queijo mussarela , cebola refogada , tomate, batata palha, purê de batata, maionese, ketchup e Cheddar",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 7,
        title: "Dog Carne de sol c/Queijo",
        price: 32,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020149_G3BM_.jpeg",
        description: "Pão, Salsicha, carne de sol , queijo mussarela , cebola refogada , tomate, batata palha, purê de batata, maionese, ketchup e Cheddar",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 8,
        title: "Dog Frango",
        price: 21,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020205_J5Z9_.jpeg",
        description: "Pão, Salsicha, frango , cebola refogada , tomate, milho, batata palha, purê de batata, maionese, ketchup, Requeijão Cremoso e Catupiry",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 9,
        title: "Dog frango c/ bacon",
        price: 23,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020209_D78U_.jpeg",
        description: "Pão, Salsicha, frango , bacon , cebola refogada , tomate, milho, batata palha, purê de batata, maionese, ketchup , Catupiry e Requeijão Cremoso .",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 10,
        title: "Dog frango c/queijo",
        price: 24,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020207_F85X_.jpeg",
        description: "Pão, Salsicha, frango , queijo mussarela, cebola refogada , tomate, milho, batata palha, purê de batata, maionese, ketchup , Catupiry e Requeijão Cremoso .",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 11,
        title: "Dog Frango c/ queijo e bacon",
        price: 25,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020207_F85X_.jpeg",
        description: "Pão, Salsicha, frango , queijo mussarela, cebola refogada , tomate, milho, batata palha, purê de batata, maionese, ketchup , Catupiry e Requeijão Cremoso .",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 55,
        title: "Dog quatro queijos",
        price: 23,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020214_5TI6_.jpeg",
        description: "Pão, Salsicha , queijo mussarela, cebola refogada , tomate, milho, batata palha, purê de batata, maionese, ketchup ,Requeijão e Cheddar",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 12,
        title: "Dog queijo coalho",
        price: 24,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020214_5TI6_.jpeg",
        description: "Pão, Salsicha , queijo mussarela, cebola refogada , tomate, milho, batata palha, purê de batata, maionese, ketchup ,Requeijão e Cheddar",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    {
        id: 13,
        title: "Dog x Tudão",
        price: 30,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020218_JC3Y_.jpeg",
        description: "Pão, 2 Salsicha, frango , calabresa ,queijo mussarela, cebola refogada , tomate, milho, batata palha, purê de batata, maionese, ketchup e catchup",
        offer: false,
        categorieId: 1,
        storage: 99999,
        disponible: true,
        categorieName: "Hotdogs",
    },

    // MOLHOS
    {
        id: 14,
        title: "Molho de Abacaxi",
        price: 2,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020229_1NIP_.jpeg",
        description: "Molho de Abacaxi",
        offer: false,
        categorieId: 3,
        storage: 99999,
        disponible: true,
        categorieName: "Molhos",
    },

    {
        id: 15,
        title: "Molho de alho",
        price: 1,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020229_1NIP_.jpeg",
        description: "Molho de alho",
        offer: false,
        categorieId: 3,
        storage: 99999,
        disponible: true,
        categorieName: "Molhos",
    },

    {
        id: 16,
        title: "Molho de bacon",
        price: 1.50,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020229_1NIP_.jpeg",
        description: "Molho de bacon",
        offer: false,
        categorieId: 3,
        storage: 99999,
        disponible: false,
        categorieName: "Molhos",
    },

    {
        id: 60,
        title: "Molho de carne",
        price: 2,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020229_1NIP_.jpeg",
        description: "Molho de carne",
        offer: false,
        categorieId: 3,
        storage: 99999,
        disponible: false,
        categorieName: "Molhos",
    },

    {
        id: 17,
        title: "Molho de ervas",
        price: 1,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020229_1NIP_.jpeg",
        description: "Molho de ervas",
        offer: true,
        categorieId: 3,
        storage: 99999,
        disponible: false,
        categorieName: "Molhos",
    },

    {
        id: 18,
        title: "Molho de limão",
        price: 1,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020229_1NIP_.jpeg",
        description: "Molho de limão",
        offer: false,
        categorieId: 3,
        storage: 99999,
        disponible: true,
        categorieName: "Molhos",
    },



    // Batata Frita

    {
        id: 19,
        title: "Batata frita M",
        price: 12,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607030949_J63D_i.jpg",
        description: "Batata frita M",
        offer: false,
        categorieId: 2,
        storage: 99999,
        disponible: true,
        categorieName: "Fritas",
    },

    {
        id: 20,
        title: "Batata frita C/ Calabresa M",
        price: 16,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607030955_1MQ1_i.jpg",
        description: "Batata frita C/ Calabresa M",
        offer: false,
        categorieId: 2,
        storage: 99999,
        disponible: true,
        categorieName: "Fritas",
    },

    {
        id: 21,
        title: "Batata frita C/ Bacon M",
        price: 16,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607030957_8WW0_i.jpg",
        description: "Batata frita C/ Bacon M",
        offer: false,
        categorieId: 2,
        storage: 99999,
        disponible: true,
        categorieName: "Fritas",
    },

    {
        id: 22,
        title: "Batata frita com bacon e calabresa M",
        price: 16,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607031000_XS58_i.jpg",
        description: "Batata frita com bacon e calabresa M",
        offer: false,
        categorieId: 2,
        storage: 99999,
        disponible: true,
        categorieName: "Fritas",
    },

    // REFRI
    {
        id: 23,
        title: "Refri coca cola 200ml",
        price: 4,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020359_84KF_.jpeg",
        description: "Refri coca cola 200ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 24,
        title: "Refri coca cola zero 200ml",
        price: 4,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020358_OXZB_.jpeg",
        description: "Refri coca cola zero 200ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 25,
        title: "Refrigerante cajuína 350ml",
        price: 6,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020345_6XWL_.jpeg",
        description: "Refri coca cola 200ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 26,
        title: "Refrigerante cajuína zero 350ml",
        price: 6,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020346_DEI5_.jpeg",
        description: "Refrigerante cajuína zero 350ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 27,
        title: "Refrigerante coca cola 1l",
        price: 9,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020340_2NO0_.jpeg",
        description: "Refrigerante coca cola 1l",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },
    {
        id: 28,
        title: "Refrigerante coca cola zero 1l",
        price: 9,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020339_9826_.jpeg",
        description: "Refrigerante coca cola zero 1l",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 29,
        title: "Refrigerante coca cola zero 350ml",
        price: 9,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020351_SZ79_.jpeg",
        description: "Refrigerante coca cola zero 350ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 30,
        title: "Refrigerante Guaraná 350ml",
        price: 6,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020348_BY5T_.jpeg",
        description: "Refrigerante Guaraná 350ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 31,
        title: "Refrigerante Guaraná 1l",
        price: 9,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020354_99Y4_.jpeg",
        description: "Refrigerante Guaraná 1l",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },


    {
        id: 32,
        title: "Refrigerante Guaraná Zero 350ml",
        price: 6,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020347_IJHZ_.jpeg",
        description: "Refrigerante Guaraná Zero 350ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 33,
        title: "Refrigerante Guaraná Zero 1l",
        price: 9,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020336_2WC9_.jpeg",
        description: "Refrigerante Guaraná Zero 1l",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 34,
        title: "Refrigerante Sukita laranja 1l",
        price: 9,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020335_4R52_.jpeg",
        description: "Refrigerante Sukita laranja 1l",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 35,
        title: "Refrigerante Fanta laranja",
        price: 6,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020335_4R52_.jpeg",
        description: "Refrigerante Fanta laranja",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 36,
        title: "Refrigerante Sprite 350ml",
        price: 6,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020343_18L1_.jpeg",
        description: "Refrigerante Sprite 350ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 37,
        title: "Refrigerante Sprite zero 350ml",
        price: 6,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020343_18L1_.jpeg",
        description: "Refrigerante Sprite zero 350ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },
    {
        id: 38,
        title: "Refrigerante Uva 350ml",
        price: 6,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020349_962X_.jpeg",
        description: "Refrigerante Uva 350ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },
    {
        id: 39,
        title: "Refri Guaraná 200ml",
        price: 4,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020400_7316_.jpeg",
        description: "Refri Guaraná 200ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },

    {
        id: 40,
        title: "Refri Guaraná Zero 200ml",
        price: 4,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020359_MVRV_.jpeg",
        description: "Refri Guaraná Zero 200ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },
    {
        id: 41,
        title: "Refri Sukita laranja 200ml",
        price: 4,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020357_0JUM_.jpeg",
        description: "Refri Sukita laranja 200ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },
    {
        id: 98,
        title: "Refri Soda 200ml",
        price: 4,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020356_05YW_.jpeg",
        description: "Refri Soda 200ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },
    {
        id: 42,
        title: "Refri Fanta uva 200ml",
        price: 4,
        photo: "https://static-images.ifood.com.br/pratos/0d6ec9ac-98a0-4ee6-948b-8d6f79c70ab0/202607020356_0NA8_.jpeg",
        description: "Refri Fanta uva 200ml",
        offer: false,
        categorieId: 4,
        storage: 99999,
        disponible: true,
        categorieName: "Refrigerantes",
    },
]

